apiVersion: v1
kind: Deployment 
metadata:
  name: redis-deployment
spec:
  metadata:
    name: redis-pod
  labels:
    name: redis-pod
    app: voting-app
  spec:
    containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
      name: redis-pod