apiVersion: v1
kind: Deployment 
metadata: 
  name: result-app-deployment
spec:
  metadata:
    name: result-app-pod
  labels:
    name: result-app-pod
    app: voting-app 
  spec:
    containers:
    - name: result-pod
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80
  replicas: 3
  selector: 
    matchLabels:
      name: result-app-pod
      app: voting-app
