apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app-deployment
spec:
  template:
    metadata:
      name: vote-app-pod
      labels:
        name: vote-app-pod
        app: voting-app 
    spec:
      containers:
      - name: vote-pod
        image: dockersamples/examplevotingapp_vote
        ports:
          - containerPort: 80
  replicas: 3
  selector: 
    matchLabels:
      app: voting-app
      name: vote-app-pod
