apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: worker-app-deployment
spec:
  template:
    metadata:
      name: worker-app-pod
      labels:
        name: worker-app-pod
        app: voting-app 
    spec:
      containers:
      - name: worker-pod
        image: dockersamples/examplevotingapp_worker
  replicas: 1
  selector:
    matchLabels:
      name: worker-app-pod
      app: voting-app 