apiVersion: v1 
kind: Service
metadata:
  name: vote-app-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30001
  selector:
    name: vote-app-pod
    app: voting-app
      