apiVersion: v1
kind: Pod
metadata:
  name: vote-app-pod
  labels:
    name: vote-app-pod
    app: voting-app 
spec:
  containers:
  - name: vote-pod
    image: dockersamples/examplevotingapp_vote
    ports:
      - containerPort: 80

  